package org.usfirst.frc3173.IgKnighters2013.utilities;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import edu.wpi.first.wpilibj.CANJaguar.SpeedReference;
import edu.wpi.first.wpilibj.can.CANTimeoutException;

/**
 * A replacement for CANJaguar which attempts to resurrect any dead Jaguars
 * automagically. Jaguars can be uninstantiated in the middle of a match if one
 * of them gets accidentally turned off (eg. if a breaker trips momentarily);
 * this will catch that happening and attempt to re-instantiate the Jaguar.
 * Not all (or even most) of the methods are implemented here; if more methods
 * are needed they can be easily included by following the example of an existing
 * wrapper method. All JavaDoc for wrapper methods is copied from the CANJaguar
 * code.
 * @author Wolfgang Faust
 */
public class CANJaguarDummy implements CANJaguar {
	/**
	 * Whether to output debug messages about the current usage.
	 */
	private static boolean DEBUG_CURRENT = false;
	/**
	 * The Jaguar represented by this class.
	 */
	protected edu.wpi.first.wpilibj.CANJaguar m_jaguar;
	/**
	 * The ID of the CANJaguar represented by this class (used to re-instantiate).
	 */
	protected int m_id;
	/**
	 * Set up a Jaguar!
	 * @param id The CAN id of the jaguar
	 * @throws CANTimeoutException Never thrown, but needed so the RobotMap generated by RobotBuilder works as expected.
	 */
	public CANJaguarDummy (int id) {
		this(id, true);
	}
	/**
	 * Make an instance of a Jaguar motor controller which can be resurrected.
	 * @param id The jaguar's ID on the CAN bus.
	 * @param slowRamp Whether the ramping should be fast or slow.
	 */
	public CANJaguarDummy (int id, boolean slowRamp) {
		m_id = id;
	}
	/**
	 * Handle a CANTimeoutException by attempting to reinstantiate the Jaguar
	 * @param e The original CANTimeoutException that caused jaguarErr() to be called.
	 */
	protected void jaguarErr(CANTimeoutException e) {
	}
	/**
	 * Attempt to (re-?)instantiate the Jaguar, printing the Exception if it fails.
	 * @return Whether the Jaguar was successfully instantiated.
	 */
	protected boolean instantiate() {
		return false;
	}
	/**
     * Set the output set-point value.
     *
     * The scale and the units depend on the mode the Jaguar is in.
     * In PercentVbus Mode, the outputValue is from -1.0 to 1.0 (same as PWM Jaguar).
     * In Voltage Mode, the outputValue is in Volts.
     * In Current Mode, the outputValue is in Amps.
     * In Speed Mode, the outputValue is in Rotations/Minute.
     * In Position Mode, the outputValue is in Rotations.
     *
     * @param outputValue The set-point to sent to the motor controller.
     */

	public void setX(double speed) {
		
	}
	/**
     * Get the status of the forward limit switch.
     *
     * @return The motor is allowed to turn in the forward direction when true.
     */
	public boolean getForwardLimitOK () {
		return false;
	}
   /**
     * Get the status of the reverse limit switch.
     *
     * @return The motor is allowed to turn in the reverse direction when true.
     */
	public boolean getReverseLimitOK () {
            return false;
	}
	public void changeControlMode(edu.wpi.first.wpilibj.CANJaguar.ControlMode mode) {
		
	}
	public void setPositionReference(edu.wpi.first.wpilibj.CANJaguar.PositionReference ref) {
		
        }
	public void configEncoderCodesPerRev(int lines) {
		
		
	}
	public void setPID(double progressive, double integral, double differential) {
		
	}
	public void configNeutralMode(edu.wpi.first.wpilibj.CANJaguar.NeutralMode mode) {
		
	}
	public double getPosition(){
		return 0;

	}
    /**
     * Get the recently set outputValue setpoint.
     *
     * The scale and the units depend on the mode the Jaguar is in.
     * In PercentVbus Mode, the outputValue is from -1.0 to 1.0 (same as PWM Jaguar).
     * In Voltage Mode, the outputValue is in Volts.
     * In Current Mode, the outputValue is in Amps.
     * In Speed Mode, the outputValue is in Rotations/Minute.
     * In Position Mode, the outputValue is in Rotations.
     *
     * @return The most recently set outputValue setpoint.
     */
	public double getX() {
		return 0;
	}
    /**
     * Get the current through the motor terminals of the Jaguar.
     *
     * @return The output current in Amps.
     */
	public double getOutputCurrent () {
		return 0;
	}
	public void setVoltageRampRate(double rampRate) {
		
	}
	public void configMaxOutputVoltage(double voltage) {
	}

	public void enableControl(double encoderInitalPosition) {
	}
	public void enableControl() {
	}

    public void disableControl() {
    }

    public double getP() {
        return 0.0;
    }

    public double getI() {
        return 0.0;
    }

    public double getD() {
        return 0.0;
    }

    public boolean getMode() {
        return false;
    }

    public double getSpeed() {
        return 0.0;
    }

    public void setSpeedReference(SpeedReference ref) {
    }
}
