// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3173.IgKnighters2016.commands;

import edu.wpi.first.wpilibj.command.Command;

import org.omg.PortableInterceptor.ObjectIdHelper;
import org.usfirst.frc3173.IgKnighters2016.Robot;

/**



 */
public class ClimberTapeSpringIn extends Command {
	
	private static boolean isFinished_now = true;
	
	
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private boolean m_in;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public ClimberTapeSpringIn(boolean in) {

    	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        m_in = in;
        
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        //requires(Robot.climber);
        
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    
    protected void initialize() {
    	
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	if (m_in){
    		Robot.climber.setTapeSpeed(-0.4);
    	}
    	else{
    		Robot.climber.setTapeSpeed(0.25);
    	}
    }
    
    // Make this return true when this Command no longer needs to run execute()
  
    public boolean isFinished() {
    	/*if (m_in){
    		if(Robot.oi.tapeStop.get() == true){
    			//instance that tape is black
    			isFinished_now = true;
    		}else{
    			//instance tape is still yellow
    			isFinished_now = false;
    		}
    		return isFinished_now;
    	}*/ 
    	return false;  			
   }	
   
    // Called once after isFinished returns true
    protected void end() { 	
    	Robot.climber.setTapeSpeed(0); 	  	 
    }
    
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    
    protected void interrupted() {
    	end();    	
    }
    
}


