// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3173.IgKnighters2016.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3173.IgKnighters2016.Robot;

/**
 *
 */
public class DriveWithJoysticks extends Command {
	
	final double MAXIMUM_SPEED = .75;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public DriveWithJoysticks() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drives);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	//if (Robot.oi.tractionControlSwitch.get()) {
    	if(Robot.oi.drivesChangeDirection.get()){
    		Robot.drives.drivePercentVbus(Robot.oi.leftJoystick.getY(),Robot.oi.rightJoystick.getY());
    	}else{
    		Robot.drives.drivePercentVbus(-Robot.oi.rightJoystick.getY(), -Robot.oi.leftJoystick.getY());
    	}
    	//} else {
    	//	Robot.drives.driveSpeed(Robot.oi.leftJoystick.getY()*MAXIMUM_SPEED,Robot.oi.rightJoystick.getY()*MAXIMUM_SPEED);
    	//}
    	//hi cosmo, call me ishmael
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
