// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc3173.IgKnighters2013;
    
import edu.wpi.first.wpilibj.*;
import org.usfirst.frc3173.IgKnighters2013.utilities.CANJaguar;
import org.usfirst.frc3173.IgKnighters2013.utilities.*;
import edu.wpi.first.wpilibj.can.CANTimeoutException;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANJaguar drivesLeftFront;
    public static CANJaguar drivesRightFront;
    public static CANJaguar drivesLeftRear;
    public static CANJaguar drivesRightRear;

    public static Compressor compressor;
    public static DigitalInput running, shooting,autoing;
    public static DigitalOutput lights;
    public static DriverStationLCD driverstation;
    //public static CANJaguar acquisitionRoller;
    //public static CANJaguar acquisitionContract;
//    public static Gyro driveGyro;
    public static CANJaguar shooterShooter;
    public static CANJaguar tilterTilter;
    //public static DoubleSolenoid storageSolenoid;
    public static Relay storageSolenoid;
    public static Relay ClimberSolenoid;//Solenoid ClimberSolenoid;
    public static Relay AcQSolenoid;
    //public static CANJaguar ClimberJaguar;
    //public static Solenoid rightClimber;
    //public static DigitalModule digitalModule;
    //public static I2C compass;
    public static I2C accelerometer;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
            drivesLeftFront = new CANJaguarLive(3);
            drivesRightFront = new CANJaguarLive(2);
            drivesLeftRear = new CANJaguarLive(5);
            drivesRightRear = new CANJaguarLive(4);
            
            //acquisitionRoller = new CANJaguarLive(15);
            //acquisitionContract = new CANJaguarLive(10);
            compressor = new Compressor(1,1);
            shooterShooter = new CANJaguarLive(6,false);
            tilterTilter = new CANJaguarLive(7);
            driverstation = DriverStationLCD.getInstance();
            running = new DigitalInput(2);
            shooting = new DigitalInput(3);
            autoing = new DigitalInput(10);
            lights = new DigitalOutput(5);
            lights.set(true);
            //digitalModule = 
            //compass = DigitalModule.getInstance(1).getI2C(67);
            System.out.println("before accel");
           // accelerometer = new I2C(DigitalModule.getInstance(1), 0x3A);
            //new ADXL345_I2C(DigitalModule.getInstance(1).getModuleNumber(), ADXL345_I2C.DataFormat_Range.k2G);
            //
            //new ADXL345_I2C(1, ADXL345_I2C.DataFormat_Range.k2G);
            System.out.println("Made it!");
        /**
         * @Todo: Fix Module and Channel numbers
         */
	    ClimberSolenoid=new Relay(2);//Now being used as lights
        //rightClimber = new Solenoid(2);	
        //driveGyro = new Gyro(8);
        storageSolenoid = new Relay(3);//DoubleSolenoid(5,4);
        AcQSolenoid = new Relay(4);
//        ClimberJaguar = new CANJaguarDummy(4);//change id
    }

}
