// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3173.COOKIECODE2018;

import com.ctre.phoenix.motorcontrol.can.TalonSRX;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX drivesLeftMaster;
    public static WPI_TalonSRX drivesRightMaster;
    public static WPI_TalonSRX drivesLeftMotor;
    public static WPI_TalonSRX drivesRightMotor;
    public static DifferentialDrive drivesDriveController;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivesLeftMaster = new WPI_TalonSRX(2);
        
        drivesRightMaster = new WPI_TalonSRX(1);

        drivesLeftMotor = new WPI_TalonSRX(4);
        
        drivesRightMotor = new WPI_TalonSRX(3);
        
        drivesDriveController = new DifferentialDrive(drivesLeftMaster, drivesRightMaster);
        drivesDriveController.setSafetyEnabled(true);
        drivesDriveController.setExpiration(0.1);
        drivesDriveController.setMaxOutput(1.0);
        
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
