/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.usfirst.frc3173.IgKnighters2013.commands;
import edu.wpi.first.wpilibj.CANJaguar;
import edu.wpi.first.wpilibj.DriverStationLCD;
import edu.wpi.first.wpilibj.can.CANTimeoutException;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3173.IgKnighters2013.Robot;
import org.usfirst.frc3173.IgKnighters2013.RobotMap;
/**
 *
 * @author Csimons2016
 */
public class ShooterInitialize extends Command {
    public ShooterInitialize(){
         // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.shooter);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    protected void initialize() {
        RobotMap.driverstation.println(DriverStationLCD.Line.kUser1,1,this.toString() + " starting");
        //RobotMap.shooterShooter.setX(-.5);
        
    }

    protected void execute() {
        //RobotMap.shooterShooter.setX(-.75);
        Robot.shooterCommand.start();
    }

    protected boolean isFinished() {
        return false;
    }

    protected void end() {

        RobotMap.shooterShooter.changeControlMode(CANJaguar.ControlMode.kSpeed);
        RobotMap.shooterShooter.setPID(1,.01,0);//10,.001 ,.001 );
        RobotMap.shooterShooter.setSpeedReference(CANJaguar.SpeedReference.kEncoder);
        RobotMap.shooterShooter.configEncoderCodesPerRev(1);
        RobotMap.shooterShooter.enableControl(0.0);
        System.out.println("Speed Mode enabled");
    }

    protected void interrupted() {
        end();
    }
    
}
