// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3173.Igknighters2015.subsystems;

import org.usfirst.frc3173.Igknighters2015.RobotMap;
import org.usfirst.frc3173.Igknighters2015.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class BinHolder extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Solenoid binHolderPneumatic = RobotMap.binHolderBinHolderPneumatic;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public boolean binHolderPneumaticState=false;

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void toggleBinHolder(){
    	binHolderPneumatic.set(!binHolderPneumaticState);
    	binHolderPneumaticState=!binHolderPneumaticState;
    	SmartDashboard.putBoolean("Bin Holder Pneumatic", binHolderPneumaticState);
    }
    
    public void openBinHolder(){
    	binHolderPneumatic.set(true);
    	SmartDashboard.putBoolean("Bin Holder Pneumatic", binHolderPneumaticState);
    }
    
    public void closeBinHolder(){
    	 binHolderPneumatic.set(false);
    	 SmartDashboard.putBoolean("Bin Holder Pneumatic", binHolderPneumaticState);
    }
}

